/**
 * Opciones de configuración para el formulario de compañía
 */

export interface IndustryOption {
  id: number;
  name: string;
}

export interface TimeZoneOption {
  label: string;
  value: string;
}

/**
 * Lista de rubros/industrias disponibles
 */
export const INDUSTRIES: IndustryOption[] = [
  { id: 5, name: "Restaurant" },
  { id: 6, name: "Tecnologic" },
  { id: 7, name: "Medical" },
  { id: 8, name: "Dentist" },
  { id: 9, name: "Psychology" },
  { id: 10, name: "Consultant" },
  { id: 11, name: "Pharmacy" },
  { id: 13, name: "Real Estate" },
  { id: 14, name: "Short-term rental properties" }
];

/**
 * Lista de zonas horarias disponibles
 */
export const TIME_ZONES: TimeZoneOption[] = [
  { label: "Afganistán", value: "Asia/Kabul" },
  { label: "Islas Åland", value: "Europe/Helsinki" },
  { label: "Albania", value: "Europe/Tirane" },
  { label: "Argelia", value: "Africa/Algiers" },
  { label: "Samoa Americana", value: "Pacific/Pago_Pago" },
  { label: "Andorra", value: "Europe/Andorra" },
  { label: "Angola", value: "Africa/Luanda" },
  { label: "Anguila", value: "America/Anguilla" },
  { label: "Antártida", value: "Antarctica/McMurdo" },
  { label: "Antigua y Barbuda", value: "America/Antigua" },
  { label: "Argentina", value: "America/Argentina/Buenos_Aires" },
  { label: "Armenia", value: "Asia/Yerevan" },
  { label: "Aruba", value: "America/Aruba" },
  { label: "Australia", value: "Australia/Sydney" },
  { label: "Austria", value: "Europe/Vienna" },
  { label: "Azerbaiyán", value: "Asia/Baku" },
  { label: "Bahamas", value: "America/Nassau" },
  { label: "Bahréin", value: "Asia/Bahrain" },
  { label: "Bangladés", value: "Asia/Dhaka" },
  { label: "Barbados", value: "America/Barbados" },
  { label: "Bielorrusia", value: "Europe/Minsk" },
  { label: "Bélgica", value: "Europe/Brussels" },
  { label: "Belice", value: "America/Belize" },
  { label: "Benín", value: "Africa/Porto-Novo" },
  { label: "Bermudas", value: "Atlantic/Bermuda" },
  { label: "Bután", value: "Asia/Thimphu" },
  { label: "República Bolivariana de Venezuela", value: "America/Caracas" },
  { label: "Bolivia", value: "America/La_Paz" },
  { label: "Bonaire, San Eustaquio y Saba", value: "America/Kralendijk" },
  { label: "Bosnia y Herzegovina", value: "Europe/Sarajevo" },
  { label: "Botsuana", value: "Africa/Gaborone" },
  { label: "Isla Bouvet", value: "Indian/Bouvet" },
  { label: "Brasil", value: "America/Sao_Paulo" },
  { label: "Territorio Británico del Océano Índico", value: "Indian/Chagos" },
  { label: "Brunéi", value: "Asia/Brunei" },
  { label: "Bulgaria", value: "Europe/Sofia" },
  { label: "Burkina Faso", value: "Africa/Ouagadougou" },
  { label: "Burundi", value: "Africa/Bujumbura" },
  { label: "Cabo Verde", value: "Atlantic/Cape_Verde" },
  { label: "Camboya", value: "Asia/Phnom_Penh" },
  { label: "Camerún", value: "Africa/Douala" },
  { label: "Canadá", value: "America/Toronto" },
  { label: "Islas Caimán", value: "America/Cayman" },
  { label: "República Centroafricana", value: "Africa/Bangui" },
  { label: "Chad", value: "Africa/Ndjamena" },
  { label: "Chile", value: "America/Santiago" },
  { label: "China", value: "Asia/Shanghai" },
  { label: "Isla de Navidad", value: "Indian/Christmas" },
  { label: "Islas Cocos", value: "Indian/Cocos" },
  { label: "Colombia", value: "America/Bogota" },
  { label: "Comoras", value: "Indian/Comoro" },
  { label: "Congo", value: "Africa/Brazzaville" },
  { label: "Congo (RDC)", value: "Africa/Kinshasa" },
  { label: "Islas Cook", value: "Pacific/Rarotonga" },
  { label: "Costa Rica", value: "America/Costa_Rica" },
  { label: "Costa de Marfil", value: "Africa/Abidjan" },
  { label: "Croacia", value: "Europe/Zagreb" },
  { label: "Cuba", value: "America/Havana" },
  { label: "Curazao", value: "America/Curacao" },
  { label: "Chipre", value: "Asia/Nicosia" },
  { label: "República Checa", value: "Europe/Prague" },
  { label: "República Democrática de Timor-Leste", value: "Asia/Dili" },
  { label: "Dinamarca", value: "Europe/Copenhagen" },
  { label: "Yibuti", value: "Africa/Djibouti" },
  { label: "Dominica", value: "America/Dominica" },
  { label: "República Dominicana", value: "America/Santo_Domingo" },
  { label: "Ecuador", value: "America/Guayaquil" },
  { label: "Egipto", value: "Africa/Cairo" },
  { label: "El Salvador", value: "America/El_Salvador" },
  { label: "Guinea Ecuatorial", value: "Africa/Malabo" },
  { label: "Eritrea", value: "Africa/Asmara" },
  { label: "Estonia", value: "Europe/Tallinn" },
  { label: "Etiopía", value: "Africa/Addis_Ababa" },
  { label: "Islas Malvinas", value: "Atlantic/Stanley" },
  { label: "Islas Feroe", value: "Atlantic/Faroe" },
  { label: "Fiyi", value: "Pacific/Fiji" },
  { label: "Finlandia", value: "Europe/Helsinki" },
  { label: "Francia", value: "Europe/Paris" },
  { label: "Guayana Francesa", value: "America/Cayenne" },
  { label: "Polinesia Francesa", value: "Pacific/Tahiti" },
  { label: "Territorios Australes Franceses", value: "Indian/Kerguelen" },
  { label: "Gabón", value: "Africa/Libreville" },
  { label: "Gambia", value: "Africa/Banjul" },
  { label: "Georgia", value: "Asia/Tbilisi" },
  { label: "Alemania", value: "Europe/Berlin" },
  { label: "Ghana", value: "Africa/Accra" },
  { label: "Gibraltar", value: "Europe/Gibraltar" },
  { label: "Grecia", value: "Europe/Athens" },
  { label: "Groenlandia", value: "America/Godthab" },
  { label: "Granada", value: "America/Grenada" },
  { label: "Guadalupe", value: "America/Guadeloupe" },
  { label: "Guam", value: "Pacific/Guam" },
  { label: "Guatemala", value: "America/Guatemala" },
  { label: "Guernsey", value: "Europe/Guernsey" },
  { label: "Guinea", value: "Africa/Conakry" },
  { label: "Guinea-Bisáu", value: "Africa/Bissau" },
  { label: "Guyana", value: "America/Guyana" },
  { label: "Haití", value: "America/Port-au-Prince" },
  { label: "Islas Heard y McDonald", value: "Indian/Heard" },
  { label: "Honduras", value: "America/Tegucigalpa" },
  { label: "RAE de Hong Kong", value: "Asia/Hong_Kong" },
  { label: "Hungría", value: "Europe/Budapest" },
  { label: "Islandia", value: "Atlantic/Reykjavik" },
  { label: "India", value: "Asia/Kolkata" },
  { label: "Indonesia", value: "Asia/Jakarta" },
  { label: "Irán", value: "Asia/Tehran" },
  { label: "Iraq", value: "Asia/Baghdad" },
  { label: "Irlanda", value: "Europe/Dublin" },
  { label: "Israel", value: "Asia/Jerusalem" },
  { label: "Jamaica", value: "America/Jamaica" },
  { label: "Jan Mayen", value: "Atlantic/Jan_Mayen" },
  { label: "Japón", value: "Asia/Tokyo" },
  { label: "Jersey", value: "Europe/Jersey" },
  { label: "Jordania", value: "Asia/Amman" },
  { label: "Kazajistán", value: "Asia/Almaty" },
  { label: "Kenia", value: "Africa/Nairobi" },
  { label: "Kiribati", value: "Pacific/Tarawa" },
  { label: "Corea", value: "Asia/Seoul" },
  { label: "Kosovo", value: "Europe/Belgrade" },
  { label: "Kuwait", value: "Asia/Kuwait" },
  { label: "Kirguistán", value: "Asia/Bishkek" },
  { label: "Laos", value: "Asia/Vientiane" },
  { label: "Letonia", value: "Europe/Riga" },
  { label: "Líbano", value: "Asia/Beirut" },
  { label: "Lesoto", value: "Africa/Maseru" },
  { label: "Liberia", value: "Africa/Monrovia" },
  { label: "Libia", value: "Africa/Tripoli" },
  { label: "Liechtenstein", value: "Europe/Vaduz" },
  { label: "Lituania", value: "Europe/Vilnius" },
  { label: "Luxemburgo", value: "Europe/Luxembourg" },
  { label: "RAE de Macao", value: "Asia/Macau" },
  { label: "Macedonia del Norte, República de", value: "Europe/Skopje" },
  { label: "Madagascar", value: "Indian/Antananarivo" },
  { label: "Malaui", value: "Africa/Blantyre" },
  { label: "Malasia", value: "Asia/Kuala_Lumpur" },
  { label: "Maldivas", value: "Indian/Maldives" },
  { label: "Mali", value: "Africa/Bamako" },
  { label: "Malta", value: "Europe/Malta" },
  { label: "Man, Isla de", value: "Europe/Isle_of_Man" },
  { label: "Islas Marshall", value: "Pacific/Majuro" },
  { label: "Martinica", value: "America/Martinique" },
  { label: "Mauritania", value: "Africa/Nouakchott" },
  { label: "Mauricio", value: "Indian/Mauritius" },
  { label: "Mayotte", value: "Indian/Mayotte" },
  { label: "México", value: "America/Mexico_City" },
  { label: "Micronesia", value: "Pacific/Pohnpei" },
  { label: "Moldavia", value: "Europe/Chisinau" },
  { label: "Mónaco", value: "Europe/Monaco" },
  { label: "Mongolia", value: "Asia/Ulaanbaatar" },
  { label: "Montenegro", value: "Europe/Podgorica" },
  { label: "Montserrat", value: "America/Montserrat" },
  { label: "Marruecos", value: "Africa/Casablanca" },
  { label: "Mozambique", value: "Africa/Maputo" },
  { label: "Myanmar", value: "Asia/Yangon" },
  { label: "Namibia", value: "Africa/Windhoek" },
  { label: "Nauru", value: "Pacific/Nauru" },
  { label: "Nepal", value: "Asia/Kathmandu" },
  { label: "Países Bajos", value: "Europe/Amsterdam" },
  { label: "Nueva Caledonia", value: "Pacific/Noumea" },
  { label: "Nueva Zelanda", value: "Pacific/Auckland" },
  { label: "Nicaragua", value: "America/Managua" },
  { label: "Níger", value: "Africa/Niamey" },
  { label: "Nigeria", value: "Africa/Lagos" },
  { label: "Niue", value: "Pacific/Niue" },
  { label: "Isla Norfolk", value: "Pacific/Norfolk" },
  { label: "Corea del Norte", value: "Asia/Pyongyang" },
  { label: "Islas Marianas del Norte", value: "Pacific/Saipan" },
  { label: "Noruega", value: "Europe/Oslo" },
  { label: "Omán", value: "Asia/Muscat" },
  { label: "Pakistán", value: "Asia/Karachi" },
  { label: "Palaos", value: "Pacific/Palau" },
  { label: "Autoridad palestina", value: "Asia/Gaza" },
  { label: "Panamá", value: "America/Panama" },
  { label: "Papúa Nueva Guinea", value: "Pacific/Port_Moresby" },
  { label: "Paraguay", value: "America/Asuncion" },
  { label: "Perú", value: "America/Lima" },
  { label: "Filipinas", value: "Asia/Manila" },
  { label: "Islas Pitcairn", value: "Pacific/Pitcairn" },
  { label: "Polonia", value: "Europe/Warsaw" },
  { label: "Portugal", value: "Europe/Lisbon" },
  { label: "Puerto Rico", value: "America/Puerto_Rico" },
  { label: "Qatar", value: "Asia/Qatar" },
  { label: "Reunión", value: "Indian/Reunion" },
  { label: "Rumanía", value: "Europe/Bucharest" },
  { label: "Rusia", value: "Europe/Moscow" },
  { label: "Ruanda", value: "Africa/Kigali" },
  { label: "San Bartolomé", value: "America/St_Barthelemy" },
  { label: "Santa Elena, Ascensión y Tristán da Cunha", value: "Atlantic/St_Helena" },
  { label: "San Cristóbal y Nieves", value: "America/St_Kitts" },
  { label: "Santa Lucía", value: "America/St_Lucia" },
  { label: "San Martín (zona francesa)", value: "America/Marigot" },
  { label: "San Pedro y Miquelón", value: "America/Miquelon" },
  { label: "San Vicente y las Granadinas", value: "America/St_Vincent" },
  { label: "Samoa", value: "Pacific/Apia" },
  { label: "San Marino", value: "Europe/San_Marino" },
  { label: "Santo Tomé y Príncipe", value: "Africa/Sao_Tome" },
  { label: "Arabia Saudí", value: "Asia/Riyadh" },
  { label: "Senegal", value: "Africa/Dakar" },
  { label: "Serbia", value: "Europe/Belgrade" },
  { label: "Seychelles", value: "Indian/Mahe" },
  { label: "Sierra Leona", value: "Africa/Freetown" },
  { label: "Singapur", value: "Asia/Singapore" },
  { label: "Sint Maarten (zona neerlandesa)", value: "America/Lower_Princes" },
  { label: "Eslovaquia", value: "Europe/Bratislava" },
  { label: "Eslovenia", value: "Europe/Ljubljana" },
  { label: "Islas Salomón", value: "Pacific/Guadalcanal" },
  { label: "Somalia", value: "Africa/Mogadishu" },
  { label: "Sudáfrica", value: "Africa/Johannesburg" },
  { label: "Georgia del Sur e Islas Sandwich del Sur", value: "Atlantic/South_Georgia" },
  { label: "Sudán del Sur", value: "Africa/Juba" },
  { label: "Sri Lanka", value: "Asia/Colombo" },
  { label: "Sudán", value: "Africa/Khartoum" },
  { label: "Surinam", value: "America/Paramaribo" },
  { label: "Svalbard", value: "Arctic/Longyearbyen" },
  { label: "Suazilandia", value: "Africa/Mbabane" },
  { label: "Suecia", value: "Europe/Stockholm" },
  { label: "Suiza", value: "Europe/Zurich" },
  { label: "Siria", value: "Asia/Damascus" },
  { label: "Taiwán", value: "Asia/Taipei" },
  { label: "Tayikistán", value: "Asia/Dushanbe" },
  { label: "Tanzania", value: "Africa/Dar_es_Salaam" },
  { label: "Tailandia", value: "Asia/Bangkok" },
  { label: "Togo", value: "Africa/Lome" },
  { label: "Tokelau", value: "Pacific/Fakaofo" },
  { label: "Tonga", value: "Pacific/Tongatapu" },
  { label: "Trinidad y Tobago", value: "America/Port_of_Spain" },
  { label: "Túnez", value: "Africa/Tunis" },
  { label: "Turquía", value: "Europe/Istanbul" },
  { label: "Turkmenistán", value: "Asia/Ashgabat" },
  { label: "Islas Turcas y Caicos", value: "America/Grand_Turk" },
  { label: "Tuvalu", value: "Pacific/Funafuti" },
  { label: "EE. UU. Islas Ultramarinas Menores de Estados Unidos", value: "Pacific/Wake" },
  { label: "Uganda", value: "Africa/Kampala" },
  { label: "Ucrania", value: "Europe/Kiev" },
  { label: "Emiratos Árabes Unidos", value: "Asia/Dubai" },
  { label: "Reino Unido", value: "Europe/London" },
  { label: "Uruguay", value: "America/Montevideo" },
  { label: "Uzbekistán", value: "Asia/Tashkent" },
  { label: "Vanuatu", value: "Pacific/Efate" },
  { label: "Ciudad del Vaticano", value: "Europe/Vatican" },
  { label: "Vietnam", value: "Asia/Ho_Chi_Minh" },
  { label: "Islas Vírgenes de EE. UU.", value: "America/St_Thomas" },
  { label: "Islas Vírgenes Británicas", value: "America/Tortola" },
  { label: "Wallis y Futuna", value: "Pacific/Wallis" },
  { label: "Yemen", value: "Asia/Aden" },
  { label: "Zambia", value: "Africa/Lusaka" },
  { label: "Zimbabue", value: "Africa/Harare" }
];

/**
 * Helper para obtener el nombre del rubro por ID
 */
export const getIndustryNameById = (id: number): string => {
  const industry = INDUSTRIES.find(ind => ind.id === id);
  return industry?.name || '';
};

/**
 * Helper para obtener el label de zona horaria por value
 */
export const getTimeZoneLabelByValue = (value: string): string => {
  const tz = TIME_ZONES.find(t => t.value === value);
  return tz?.label || value;
};
